### ISSUE TITLE
Bug: purgeStale sometimes gets stuck in an infinite loop

### ISSUE THREAD

**Issue by javiergonzalezGenially** [isaacs/node-lru-cache#209] opened 2022-03-10 09:39 UTC
We found out that since we updated to v7 sometimes lru-cache would get stuck inside the purgeStale function

(lame) test
```
const LRU = require("lru-cache");

const sleep = (m) => new Promise((r) => setTimeout(r, m));
jest.setTimeout(50000);

it("works", async () => {
  const expirationTime = 1;
  const accessCache = new LRU({
    max: 66000,
    ttl: expirationTime,
    ttlResolution: 100,
    updateAgeOnGet: true,
  });
  console.log("start");

  for (let i = 0; i < 600; i++) {
    // console.log(i);
    await sleep(10);
    const rnd = Math.random() * 3;
    const v = i % 10;

    if (rnd < 1) {
      accessCache.set(v, v);
    } else if (rnd < 2) {
      accessCache.get(v);
    } else {
      console.log("purge start");
      accessCache.purgeStale();
      console.log("purge end");
    }
  }

  console.log("end");
});
```

you will see it gets stuck in purge start

The solution seems to be to make the purgeStale function "cache" the items to delete and delete it after the rindexes iteration, or else it may get stuck in an infinite iteration

```
purgeStale () {
  const toDelete = [];
  for (const i of this.rindexes({ allowStale: true })) {
    if (this.isStale(i)) {
      toDelete.push(this.keyList[i]);
    }
  }

  toDelete.forEach(k => this.delete(k));

  return toDelete.length > 0
}
```

**Comment by sheepa** [comment] 2022-03-10 17:57
I can confirm this bug.

**Comment by isaacs** [comment] 2022-03-10 19:08
Ahh, yes, because delete changes the linked list order.  Good catch and root cause.  Will fix shortly.

**Comment by isaacs** [comment] 2022-03-10 19:26
fixed on 7.4.3 by accident, on 7.4.4 on purpose 😬

**Closed by isaacs** 2022-03-10 19:26 UTC

**Comment by isaacs** [comment] 2022-03-10 19:35
backported to other 7.x versions

**Comment by palashkulsh** [comment] 2023-03-17 16:33
im not able to get my head around why infinite loop leads to infinite getpid syscalls as shown https://github.com/nodejs/node/issues/42277 . any ideas?

**Comment by isaacs** [comment] 2023-03-17 21:54
@palashkulsh Idk, you'd have to ask them. LRUCache doesn't do any getpid() calls.
